# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YJNetworkingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YJNetworkingDemo

  target 'YJNetworkingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YJNetworkingDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'
pod 'YYCache'
end
